name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily
  workflow_dispatch:      # Allow manual run

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: alizahh-7
          outputs: |
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=#39FF14&dates=true
      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
